path:
  result_path: /home/yanrui/code/CLIPBased_TAD/result
  train_data_path: /data/WWADL/dataset/all_30_3
  test_data_path:
  dataset_path: /data/WWADL/dataset/all_30_3
  dataset_root_path: /data/WWADL/processed_data
  data_path:
  clip_embed_path: /home/yanrui/code/CLIPBased_TAD/model/CLIPTAD/preTrain_Emb/clipEmbedding_withMamba-epoch-99.pt

model:
  name: CLIP
  num_classes: 30
  backbone_name: TAD 
  model_set: ""
  priors: 128 # 128
  layer_num: 3 # 3
  embedding: CLIP 
  isPreTrain: True
  mode: test
  downscale: cnn
# mode: test/train
# downscale: mamba/cnn
# embedding: TSSE / CNN / CLIP
# backbone: mamba(layer_num = 5, priors = 256) / TAD

training:
  batch_size: 8
  lw: 10
  cw: 1
  num_epoch: 80
  opt_method: adamw
  lr_rate: 4e-05
  lr_rate_adjust_epoch: 30 
  lr_rate_adjust_factor: 0.5
  weight_decay: 1e-3
  device: cuda
  clip_emb_loss: kl
  train_clip_emb: yes
  
  
  

testing:
  top_k: 1
  conf_thresh: 0.01
  nms_thresh: 0.5
  nms_sigma: 0.95



dataset:
  clip_length: 1500
  data_length: 2048
  in_channels: {
            "wifi": 270,
            "imu": 30
        }
  
